# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

default_platform(:ios)

platform :ios do
  desc "Build IPA for Firebase App Distribution"
  lane :build_ipa do
    match(type: "appstore")

    build_app(
  	scheme: "tunemusicscheme", 
  	export_method: "ad-hoc", 
  	clean: true,
  	output_directory: "./build",
 	 output_name: "TuneMusic.ipa"
    )

  end
end

