name: iOS Build for Simulator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: pod install

      - name: Create build folder
        run: mkdir -p build

      - name: Build app for Simulator (no signing required)
        run: |
          xcodebuild \
            -project TunesMusic.xcodeproj \
            -scheme TunesMusic \
            -sdk iphonesimulator \
            -configuration Debug \
            -archivePath build/TunesMusic.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Build succeeded
        run: echo "iOS simulator build completed successfully"

      - name: Upload .xcarchive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TunesMusic-archive
          path: build/TunesMusic.xcarchive
